# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       dbus-glib
Summary:    GLib bindings for D-Bus
Version:    0.92
Release:    1
Group:      System/Libraries
License:    AFL/GPL
URL:        http://www.freedesktop.org/software/dbus/
Source0:    http://dbus.freedesktop.org/releases/dbus-glib/%{name}-%{version}.tar.gz
Source100:  dbus-glib.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  libtool
BuildRequires:  expat-devel
BuildRequires:  gettext
BuildRequires:  autoconf


%description
D-Bus add-on library to integrate the standard D-Bus library with
the GLib thread abstraction and main loop.



%package devel
Summary:    Libraries and headers for the D-Bus GLib bindings
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Headers and static libraries for the D-Bus GLib bindings


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-tests \
    --enable-verbose-mode=yes \
    --enable-asserts=yes \
    --disable-gtk-doc

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
gzip ChangeLog
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc NEWS COPYING
%{_libdir}/*glib*.so.*
%{_bindir}/dbus-binding-tool
/etc/bash_completion.d/dbus-bash-completion.sh
/usr/libexec/dbus-bash-completion-helper
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%doc ChangeLog.gz
%doc %{_datadir}/gtk-doc/html/dbus-glib
%{_libdir}/lib*.so
%{_libdir}/pkgconfig/dbus-glib-1.pc
%{_includedir}/dbus-1.0/dbus/*
%{_mandir}/man1/*
# << files devel

